###########
# site.title

title:    'RoboFarm: Automated Farming with Reinforcement Learning'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-slate